from playwright.sync_api import sync_playwright
p = sync_playwright().start()
b = p.chromium.launch(headless=True)
page = b.new_page()
page.set_extra_http_headers({'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'})
page.goto('https://console.groq.com/keys')
page.wait_for_timeout(3000)
page.screenshot(path='groq_keys_check.png')
print('Screenshot saved')
b.close()
p.stop()
