"""
Report Model
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime, JSON, ForeignKey, Text, Boolean
from sqlalchemy.orm import relationship
from core.database import Base

class Report(Base):
    __tablename__ = "reports"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    description = Column(Text)
    
    # Content
    report_type = Column(String, default="dashboard")  # dashboard, dataset, custom
    source_id = Column(Integer)  # dashboard_id or dataset_id
    
    # Sections
    sections = Column(JSON, default=[])
    
    # Format settings
    formats = Column(JSON, default=["pdf"])  # pdf, pptx, excel, html
    template = Column(String, default="modern")
    include_raw_data = Column(Boolean, default=False)
    
    # Branding
    branding = Column(JSON, default={
        "logo_url": None,
        "primary_color": "#3b82f6",
        "cover_page": True,
        "footer_text": "Generated by InsightGenius"
    })
    
    # Owner
    owner_id = Column(Integer, ForeignKey("users.id"))
    owner = relationship("User", back_populates="reports")
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    schedules = relationship("ScheduledReport", back_populates="report", cascade="all, delete-orphan")

class ScheduledReport(Base):
    __tablename__ = "scheduled_reports"
    
    id = Column(Integer, primary_key=True, index=True)
    report_id = Column(Integer, ForeignKey("reports.id"))
    report = relationship("Report", back_populates="schedules")
    
    # Schedule
    name = Column(String)
    frequency = Column(String, nullable=False)  # daily, weekly, monthly, custom
    cron_expression = Column(String)  # For custom schedules
    
    # Recipients
    recipients = Column(JSON, nullable=False)  # List of emails
    subject = Column(String)
    message = Column(Text)
    
    # Active status
    is_active = Column(Boolean, default=True)
    
    # Last run
    last_run_at = Column(DateTime)
    last_run_status = Column(String)
    last_run_error = Column(Text)
    next_run_at = Column(DateTime)
    
    created_at = Column(DateTime, default=datetime.utcnow)
